ARCHS = arm64 armv7s armv7
GO_EASY_ON_ME = 1


include theos/makefiles/common.mk

BUNDLE_NAME = MultitaskingGesturesSettings
MultitaskingGesturesSettings_FILES = MultitaskingGesturesSettings.mm
MultitaskingGesturesSettings_INSTALL_PATH = /Library/PreferenceBundles
MultitaskingGesturesSettings_FRAMEWORKS = Foundation UIKit
MultitaskingGesturesSettings_PRIVATE_FRAMEWORKS = Preferences

include $(THEOS_MAKE_PATH)/bundle.mk